version: '3.8'
services:
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - infra-net

  web_1:
    build:
      context: ./web
    image: web-app:latest
    hostname: web_1
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - infra-net

  web_2:
    build:
      context: ./web
    image: web-app:latest
    hostname: web_2
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - infra-net

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: project-nginx:latest
    hostname: nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - web_1
      - web_2
    restart: unless-stopped
    networks:
      - infra-net

volumes:
  redis-data:
    name: bd

networks:
  infra-net:
    name: infra-net
    driver: bridge
